[workspace]
resolver = "2"

members = [
    "circuit_mersenne_field",
    "wrapper",
    "wrapper_generator"
]


[workspace.package]
version = "0.1.0"
edition = "2024"
authors = ["The Matter Labs Team <hello@matterlabs.dev>"]
homepage = "https://zksync.io/"
repository = "https://github.com/matter-labs/zkos-wrapper/"
license = "MIT OR Apache-2.0"
keywords = ["blockchain", "zksync", "zk", "risc-v"]
categories = ["cryptography"]


[workspace.dependencies]

circuit_mersenne_field = { path = "circuit_mersenne_field"}

boojum = { version = "=0.32.2", features = ["log_tracing"] }
bellman = { package = "zksync_bellman", version = "=0.32.2"}
rescue_poseidon = "=0.32.2"
snark_wrapper = "=0.32.2"

# boojum = { path = "../zksync-crypto/crates/boojum"}
# bellman = { path = "../zksync-crypto/crates/bellman", package="zksync_bellman"}
# rescue_poseidon = { path = "../zksync-crypto/crates/rescue-poseidon"}
# snark_wrapper = { path = "../zksync-crypto/crates/snark-wrapper"}


final_risc_verifier = {git="https://github.com/matter-labs/zksync-airbender.git", package="final_reduced_risc_v_machine_verifier", features=["proof_utils"], tag = "v0.4.0"}
reduced_risc_verifier = {git="https://github.com/matter-labs/zksync-airbender.git", package="reduced_risc_v_log_23_machine_verifier", features=["proof_utils"], tag = "v0.4.0"}
blake_verifier = {git="https://github.com/matter-labs/zksync-airbender.git", package="blake2_with_compression_verifier", features=["proof_utils"], tag = "v0.4.0"}
execution_utils = {git="https://github.com/matter-labs/zksync-airbender.git", package="execution_utils", tag = "v0.4.0"}
setups = {git="https://github.com/matter-labs/zksync-airbender.git", package="setups", tag = "v0.4.0"}
mersenne_field = {git="https://github.com/matter-labs/zksync-airbender.git", package="field", tag = "v0.4.0"}
zkos_verifier_generator = {git="https://github.com/matter-labs/zksync-airbender.git", package="verifier_generator", tag = "v0.4.0"}
prover = {git="https://github.com/matter-labs/zksync-airbender.git", package="prover", tag = "v0.4.0"}

# final_risc_verifier = {path="../zksync-airbender/circuit_defs/final_reduced_risc_v_machine/verifier", package="final_reduced_risc_v_machine_verifier", features=["proof_utils"]}
# reduced_risc_verifier = {path="../zksync-airbender/circuit_defs/reduced_risc_v_log_23_machine/verifier", package="reduced_risc_v_log_23_machine_verifier", features=["proof_utils"]}
# blake_verifier = {path="../zksync-airbender/circuit_defs/blake2_with_compression/verifier", package="blake2_with_compression_verifier", features=["proof_utils"]}
# execution_utils = {path="../zksync-airbender/execution_utils"}
# setups = {path="../zksync-airbender/circuit_defs/setups"}
# mersenne_field = {path="../zksync-airbender/field", package="field"}
# zkos_verifier_generator = {path="../zksync-airbender/verifier_generator", package="verifier_generator"}
# prover = {path="../zksync-airbender/prover", package="prover"}


serde_json = { version = "*" }
serde = { version = "1", default-features = false, features = ["derive", "alloc"]}
clap = { version = "4.5.21", features = ["derive"] }
sha3 = "*"
rand = "0.8"

# Used for GPU proving.
shivini = "=0.154.7"
proof-compression = "=0.154.7"
zksync-gpu-prover = "=0.154.7"

[profile.release.package."blake2_with_compression_verifier"]
opt-level = 1
codegen-units = 256
overflow-checks = true

[profile.release]
lto = false
# This is needed for zksync-airbender crates to compile in a reasonable time for x86-64-unknown-linux-gnu
overflow-checks = true
