cargo-features = ["edition2024"]

[package]
name = "zkos-wrapper"
version = "0.1.0"
edition = "2024"

[dependencies]
boojum = { git = "https://github.com/matter-labs/zksync-crypto.git", package="boojum", branch = "ad_zkos_wrapper" }
# boojum = { path = "../zksync-crypto/crates/boojum"}
zkos_verifier = {git="https://github.com/matter-labs/air_compiler.git", package="verifier", branch="ad_zkos_wrapper", features=["proof_utils"]}
# zkos_verifier = {path="../air_compiler/verifier", package="verifier", features=["proof_utils"]}
# cli = {git="https://github.com/matter-labs/air_compiler.git", package="tools/cli", branch="ad_zkos_wrapper", features=["proof_utils"]}
# cli = {path="../air_compiler/tools/cli"}
serde_json = { version = "*" }
serde = { version = "1", default-features = false, features = ["derive", "alloc"]}

[dev-dependencies]
rand = "0.8.4"
hex = "0.4.3"
zkos_verifier_worker = { path = "../air_compiler/worker", package="worker" }