[licenses]
allow = [
    "Apache-2.0",
    "Apache-2.0 WITH LLVM-exception",
    "MIT",
    "MPL-2.0",
    "BSD-2-Clause", 
    "BSD-3-Clause",         
    "Zlib",                  
    "CDDL-1.0",              
    "ISC",
    "Unicode-3.0",
    "CC0-1.0",
]

