[advisories]
ignore = [
    "RUSTSEC-2024-0388",  
    "RUSTSEC-2024-0384",  
    "RUSTSEC-2024-0370",  
]
[bans]
multiple-versions = "warn"
deny = []
skip = []
skip-tree = []

workspace-default-features = "allow"
external-default-features = "allow"

[sources]
unknown-registry = "warn"
unknown-git = "warn"

allow-registry = ["https://github.com/rust-lang/crates.io-index"]

[licenses]
allow = [
    "Apache-2.0",
    "Apache-2.0 WITH LLVM-exception",
    "MIT",
    "MPL-2.0",
    "BSD-2-Clause", 
    "BSD-3-Clause",         
    "Zlib",                  
    "CDDL-1.0",              
    "ISC",
    "Unicode-3.0",
    "CC0-1.0",
]

