# Used in pull requests

name: Cargo deny check
on: pull_request
permissions: read-all
jobs:
  cargo-deny:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
    - uses: EmbarkStudios/cargo-deny-action@34899fc7ba81ca6268d5947a7a16b4649013fea1 # v2.0.11
      with:
        command-arguments: "--allow unmaintained --hide-inclusion-graph"
